/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class loader_CLoader */

#ifndef _Included_loader_CLoader
#define _Included_loader_CLoader
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     loader_CLoader
 * Method:    Load
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_loader_CLoader_Load
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
